[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
jox = "5xWrz1tgbg3VdyfCfiHQVJnQ4XfFX13Y7L2PT75Yq4GJ"
[programs.devnet]
jox = "5xWrz1tgbg3VdyfCfiHQVJnQ4XfFX13Y7L2PT75Yq4GJ"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
